# DB Connection Setting
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    maxWait: 1
    maxActive: 2
    minIdle: 1
    maxIdle: 1
    maxLifetime: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 60000
  profiles:
    active: development


# message configuration
sms:
  baseurl: http://localhost:8084/sms/
  receiveurl: http://localhost:8080/receive/
  smsurl: http://120.55.193.51:8098/smtp/http/submit
  username: fjsw
  userPassword: Z8D0OWPF06IDBFXS
  serviceCode: fjsw


# LOGGING
logging:
  #file: log.txt
  level:
    org.springframework.web.client: DEBUG
    com.shuwang: DEBUG
